name: 'Orbit - Setup Orbit CI agent'
description: 'Sets up Orbit CI agents in your Github Actions workflow'
author: 'Orbit CI'

inputs:
  orbitci_server_addr:
    description: 'The address of the Orbit CI server to connect to'
    required: false
    default: 'api.us.orbit.ci'

  orbitci_api_token:
    description: 'The API token used to publish events to Orbit CI'
    required: true

  version:
    description: 'The version of Orbit CI binaries to install.'
    required: false
    default: 'v0.12.0'

  releases_repo:
    description: 'The repository name containing Orbit CI release artifacts'
    required: false
    default: 'agent-releases'

  env_allowlist:
    description: |
      Comma-separated list of user-defined environment variables to capture and include in telemetry.
      Each env var name must begin with `ORBITCI_USER_`. E.g. `ORBITCI_USER_CI_STAGE,ORBITCI_USER_PIPELINE_VERSION`
    required: false
    default: ''

outputs:
  version:
    description: 'The version of the Orbit CI binaries that were installed'

runs:
  using: 'node20'
  main: 'dist/setup/index.js'
  post: 'dist/teardown/index.js'

permissions:
  actions: read
